version: '3.18'

services:

  postgres_db:
    image: postgres:alpine
    restart: always
    networks:
      - local
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres

  
  pg_admin:
    image: dpage/pgadmin4
    networks:
      - local
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 
      PGADMIN_DEFAULT_PASSWORD: world





networks:
  local:
    name: local
    driver: bridge



